ALTER TABLE documents
  ADD COLUMN storage_key VARCHAR(512) NOT NULL DEFAULT '',
  ADD COLUMN content_type VARCHAR(128) NOT NULL DEFAULT 'application/pdf',
  ADD COLUMN source VARCHAR(32) NOT NULL DEFAULT 'UPLOAD',
  ADD COLUMN upload_status VARCHAR(32) NOT NULL DEFAULT 'UPLOADED';
